import { StyleSheet, Dimensions } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    alignContent: 'center',
    marginTop: 50,
    marginHorizontal: 15,
  },
  header: {
    height: 60,
    paddingTop: 5,
    marginBottom: 5,
  },
  name: {
    marginLeft: 45,
    fontSize: 24,
    // fontWeight: 'bold',
    color: 'darkblue',
  },
  personalHeader: {
    marginLeft: 9,
    fontSize: 24,
    // fontWeight: 'bold',
    color: 'darkblue',
  },
  SearchBar: {
    flex: 9,
    paddingTop: 5,
    paddingLeft: 4,
    paddingRight: 0,
    marginBottom: 10,
    justifyContent: 'center',
  },
  nameheader: {
    flex: 9,
    alignItems: 'center',
    width: 'auto',
    borderRadius: 50,
    justifyContent: 'center',
  },
  genre: {
    flex: 1,
    marginLeft: 10,
    marginRight: 10,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  dropdowncontainer: {
    width: '100%',
    fontSize: Dimensions.get('window').width * 0.03,
    height: Dimensions.get('window').width * 0.03 + 10,
    borderRadius: 5,
    backgroundColor: '#E0E0E0',
  },
  dropdown: {
    flex: 0.1,
    marginTop: Dimensions.get('window').height * -0.01 - 33,
    width: '72%',
  },
  dropdowntext: {
    width: Dimensions.get('window').width * 0.3,
    fontSize: Dimensions.get('window').width * 0.03,
    color: 'black',
    height: Dimensions.get('window').width * 0.03 + 10,
    borderRadius: 5,
    textAlign: 'center',
    textAlignVertical: 'center',
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginLeft: Dimensions.get('window').width * 0.2,
  },
  body: {
    flex: 1,
  },
  contact: {
    flex: 7,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  contactleft: {
    width: '35%',
    justifyContent: 'space-between',

  },
  contactright: {
    width: '63%',
    justifyContent: 'space-between',
  },
  details: {
    height: 80,
    borderWidth: 1,
    borderColor: '#bfbebe',
    marginTop: 5,
    marginBottom: 20,
    borderRadius: 5,
  },
  underline: {
    lineHeight: 50,
    marginLeft: 10,
  },
  headerInput: {
    width: 'auto',
    height: 40,
    paddingVertical: 3,
    borderColor: '#E0E0E0',
    borderWidth: 2,
    borderRadius: 20,
    textAlign: 'center',
    fontSize: 20,
    fontWeight: 'bold',
  },
  input: {
    width: '100%',
    fontSize: 16,
    color: 'black',
    height: 35,
    borderRadius: 5,
    marginLeft: 10,
    textAlign: 'left',
    textAlignVertical: 'center',
  },
  text: {
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 'bold',
    marginTop: Dimensions.get('window').width * 0.001,
    fontSize: Dimensions.get('window').width * 0.03,
  },
  image: {
    width: 85,
    height: 85,
    alignItems: 'center',
    marginTop: 5,
    backgroundColor: '#4169E1',
  },
  footer: {
    height: 'auto',
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
  },
  sentButton: {
    borderRadius: 30,
    width: 297,
    height: 48,
    paddingVertical: 8,
    marginVertical: 51,
    elevation: 20,
    shadowColor: '#000',
  },
  unsentButton: {
    borderRadius: 30,
    width: 297,
    height: 48,
    paddingVertical: 8,
    marginVertical: 51,
    backgroundColor: '#D4D4D4',
    elevation: 20,
    shadowColor: '#000',
  },
  sentButtonText: {
    fontSize: 24,
    textAlign: 'center',
    color: '#FBEEAC',
    fontWeight: 'bold',
  },
  unsentButtonText: {
    fontSize: 24,
    textAlign: 'center',
    color: '#737373',
    fontWeight: 'bold',
  },
  imageButton: {
    width: 160,
    height: 40,
    alignItems: 'center',
    borderRadius: 4,
    marginTop: 5,
    flexDirection: 'row',
    backgroundColor: '#28527A',
  },
  list: {
    width: '60%',
    alignItems: 'center',
    borderRadius: 35,
    justifyContent: 'center',
    backgroundColor: 'black',
    paddingTop: 3,
  },
  listText: {
    fontSize: 21.5,
    textAlign: 'center',
    fontStyle: 'italic',
    color: 'white',
    textDecorationLine: 'underline',
    textShadowColor: 'purple',
    textShadowRadius: 1,
  },
  listButton: {
    marginTop: 40,
    backgroundColor: '#009688',
  },
  roundbutton: {
    marginHorizontal: Dimensions.get('window').width * 0.23,
    alignItems: 'center',
    justifyContent: 'center',
    width: 200,
    height: 200,
    backgroundColor: '#bfbebe',
    borderRadius: 100,
  },
  roundbuttonText: {
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontSize: 30,
    fontWeight: 'bold',
  },
  choose: {
    flex: 1,
    marginVertical: 10,
  },
  genrebutton: {
    marginHorizontal: Dimensions.get('window').width * 0.05,
    alignItems: 'center',
    justifyContent: 'center',
    width: 150,
    height: 150,
    backgroundColor: '#bfbebe',
    borderRadius: 75,
  },
  genrebuttonText: {
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontSize: 30,
    fontWeight: 'bold',
  },
  inputbox: {
    height: 40,
    borderWidth: 1,
    borderColor: '#bfbebe',
    marginTop: 5,
    marginBottom: 20,
    borderRadius: 5,
  },
  bodyforCostAndLimitnum: {
    flexDirection: 'row',
  },
  CostTitle: {
    flex: 1.4,
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 5,
  },
  LimitnumTitle: {
    flex: 1.3,
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 5,
  },
  CostBox: {
    width: Dimensions.get('window').width * 0.37,
    height: 40,
    borderWidth: 1,
    borderColor: '#bfbebe',
    marginTop: 5,
    marginBottom: 20,
    borderRadius: 5,
  },
  LimitnumBox: {
    width: Dimensions.get('window').width * 0.37,
    height: 40,
    borderWidth: 1,
    borderColor: '#bfbebe',
    marginTop: 5,
    marginBottom: 20,
    marginLeft: 50,
    borderRadius: 5,
  },
  CostAndLimitnumText: {
    width: '100%',
    fontSize: 14,
    fontWeight: 'bold',
    color: 'black',
    height: 35,
    borderRadius: 5,
    textAlign: 'left',
    textAlignVertical: 'center',
  },
  inputboxText: {
    fontSize: 16,
    fontWeight: 'bold',
    alignItems: 'flex-start',
    textAlign: 'left',
    marginLeft: 5,
  },
  Cloudicon: {
    marginTop: 9,
    color: 'white',
    fontSize: 14,
    marginLeft: 8,
  },
  icon: {
    marginLeft: 20,
    marginTop: 10,
  },
  categorybutton: {
    flexWrap: 'wrap',
    flexDirection: 'row',
  },
  Card1: {
    height: 270,
    width: 185,
    borderRadius: 10,
    shadowColor: '#bfbebe',
    marginHorizontal: 6,
    marginBottom: 65,
  },
  Card2: {
    height: 270,
    width: 190,
    borderWidth: 1,
    borderColor: '#bfbebe',
    borderRadius: 10,
    shadowColor: '#bfbebe',
    marginTop: 15,
    marginBottom: 30,
    marginHorizontal: 2,
    // backgroundColor: '#bfbebe',
  },
  CardInMore: {
    height: 270,
    width: 190,
    borderWidth: 1,
    borderColor: '#bfbebe',
    borderRadius: 10,
    shadowColor: '#bfbebe',
    marginTop: 15,
    marginBottom: 30,
    marginHorizontal: 2.5,
    // backgroundColor: '#bfbebe',
  },
  CardInPersonal: {
    height: 270,
    width: 190,
    borderWidth: 1,
    borderColor: '#bfbebe',
    borderRadius: 10,
    shadowColor: 'darkgrey',
    marginTop: 15,
    marginBottom: 2,
    marginLeft: 13.5,
    // backgroundColor: '#bfbebe',
  },
  CardTitle: {
    textAlign: 'center',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
  },
  CardDetails: {
    marginHorizontal: 9,
    flexDirection: 'row',
  },
  CardText: {
    fontSize: 12,
  },
  CardIcon: {
    alignContent: 'flex-start',
  },
  pic: {
    // width: PixelRatio.getPixelSizeForLayoutSize(76),
    // height: PixelRatio.getPixelSizeForLayoutSize(76),
    borderRadius: 10,
    backgroundColor: '#E0E0E0',
    aspectRatio: 1,
  },
  more: {
    textAlign: 'right',
    justifyContent: 'flex-end',
    textDecorationLine: 'underline',
  },
  btnPress: {
    height: 40,
    width: 90,
    backgroundColor: '#28527A',
    justifyContent: 'center',
    borderRadius: 5,
    margin: 10,
  },
  btnNormal: {
    height: 40,
    width: 90,
    justifyContent: 'center',
    borderRadius: 5,
    backgroundColor: '#E5EBF1',
    margin: 10,
  },
  btnText: {
    textAlign: 'center',
    fontSize: 16,
    color: '#28527A',
  },
  btnPText: {
    textAlign: 'center',
    fontSize: 16,
    color: '#FBEEAC',
  },
  searchBtn: {
    width: 100,
    height: 70,
  },
  CardDetail: {
    height: '100%',
    width: '100%',
    shadowColor: '#bfbebe',
    marginTop: 10,
    marginBottom: 65,
  },
  bigpic: {
    width: 350,
    height: 350,
    alignContent: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    backgroundColor: '#E0E0E0',
  },
  DetailTitle: {
    textAlign: 'left',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },
  personalbtn: {
    width: 115,
    height: 40,
    color: 'transparent',
    fontWeight: '500',
    borderWidth: 1,
    borderColor: '#28527A',
    borderRadius: 20,
    flexDirection: 'row',
    paddingVertical: 8,
    paddingHorizontal: 29,
    marginLeft: 10,
    marginRight: 10,
  },
  personalbtnText: {
    color: '#CBD8E4',
    fontSize: 16,
    fontWeight: 'bold',
    opacity: 0.5,
    textAlign: 'center',
    textAlignVertical: 'center',
  },
  personalbtnPress: {
    borderRadius: 20,
    flexDirection: 'row',
    paddingVertical: 8,
    paddingHorizontal: 29,
    marginLeft: 10,
    marginRight: 10,
    alignItems: 'flex-start',
    backgroundColor: '#1784B2',
    width: 115,
    height: 40,
    borderWidth: 1,
    borderColor: '#28527A',
  },
  personalbtnPressText: {
    color: '#FBEEAC',
    fontSize: 16,
    fontWeight: 'bold',
  },
  personalmanagebtnPressText: {
    color: '#FBEEAC',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: -10,
    marginRight: -10,
  },
  personalmanagebtnText: {
    color: '#CBD8E4',
    fontSize: 16,
    fontWeight: 'bold',
    opacity: 0.5,
    textAlign: 'center',
    textAlignVertical: 'center',
    marginLeft: -10,
    marginRight: -10,
  },
  Card3: {
    height: 115,
    width: Dimensions.get('window').width * 0.9,
    marginHorizontal: 20,
    borderRadius: 10,
    borderBottomWidth: 2,
    borderBottomEndRadius: 10,
    borderEndColor: '#bfbebe',
    marginTop: 15,
    flexDirection: 'row',
  },
  Card3pic: {
    width: 115,
    height: 112,
    borderRadius: 10,
    backgroundColor: '#E0E0E0',
  },
  Card3Title: {
    marginLeft: 10,
    textAlign: 'left',
    justifyContent: 'center',
    fontWeight: 'bold',
  },
  Card3Details: {
    marginHorizontal: 10,
    marginTop: 7,
    flexDirection: 'row',
    alignContent: 'space-around',
  },
  Card3Text: {
    fontSize: 12,
  },
  messageBox: {
    width: Dimensions.get('window').width * 0.85,
    height: 100,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: '#bfbebe',
  },
  managebtn: {
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 29,
    marginLeft: 150,
    marginRight: 10,
    alignItems: 'flex-start',
    backgroundColor: '#1784B2',
  },
  managebtnText: {
    marginTop: 2,
    color: 'yellow',
    fontSize: 16,
    fontWeight: 'bold',
  },
  participantsBox: {
    width: Dimensions.get('window').width * 0.85,
  },
});
