import {
  FontAwesome,
  MaterialCommunityIcons,
  FontAwesome5,
  MaterialIcons,
  Ionicons,
  AntDesign,
} from '@expo/vector-icons';

export default [
  {
    title: '行政處室',
    icon: FontAwesome,
    iconName: 'building',
    haveEvent: true,
    color: '#10B981',
    border: '#047857',
  },
  {
    title: '系館',
    icon: FontAwesome5,
    iconName: 'school',
    haveEvent: false,
    color: '#0077E6',
    border: '#004282',
  },
  {
    title: '體育場所',
    icon: MaterialCommunityIcons,
    iconName: 'weight-lifter',
    haveEvent: false,
    color: '#EF4444',
    border: '#B91C1C',
  },
  {
    title: '自動繳費機',
    icon: MaterialIcons,
    iconName: 'payment',
    haveEvent: false,
    color: '#EAB308',
    border: '#A16207',
  },
  {
    title: '社團活動區',
    icon: Ionicons,
    iconName: 'md-people-circle',
    haveEvent: false,
    color: '#F43F5E',
    border: '#BE123C',
  },
  {
    title: '宿舍',
    icon: MaterialIcons,
    iconName: 'house',
    haveEvent: false,
    color: '#84CC16',
    border: '#4D7C0F',
  },
  {
    title: '景點',
    icon: FontAwesome5,
    iconName: 'camera-retro',
    haveEvent: false,
    color: '#06B6D4',
    border: '#0E7490',
  },
  {
    title: '公廁',
    icon: MaterialIcons,
    iconName: 'wc',
    haveEvent: false,
    color: '#F59E0B',
    border: '#B45309',
  },
  {
    title: '公車站',
    icon: MaterialCommunityIcons,
    iconName: 'bus-stop',
    haveEvent: false,
    color: '#0EA5E9',
    border: '#0369A1',
  },
  {
    title: '校內店家',
    icon: AntDesign,
    iconName: 'isv',
    haveEvent: false,
    color: '#6366F1',
    border: '#4338CA',
  },
  {
    title: '校外店家',
    icon: MaterialCommunityIcons,
    iconName: 'food-fork-drink',
    haveEvent: false,
    color: '#A855F7',
    border: '#7E22CE',
  },
  {
    title: 'Ubike',
    icon: MaterialCommunityIcons,
    iconName: 'bike',
    haveEvent: false,
    color: '#F97316',
    border: '#C2410C',
  },
];
