import { StyleSheet, Dimensions } from 'react-native';

export default StyleSheet.create({
  avatar: {
    margin: 10,
    width: 60,
    height: 60,
    borderRadius: 30,
    borderBottomWidth: 2,
    borderBottomEndRadius: 10,
    borderEndColor: '#bfbebe',
  },
  container: {
    flex: 1,
    flexDirection: 'column',
    alignContent: 'center',
    paddingTop: 50,
    paddingHorizontal: 15,
    backgroundColor: '#fafafa',
    // marginHorizontal: Dimensions.get('window').width * 0.07,
  },
  DeletebtnInManage: {
    backgroundColor: '#eb6f6f',
    width: 70,
    height: 35,
    borderRadius: 30,
    marginHorizontal: 5,
    marginVertical: 25,
  },
  DeletebtnInManageText: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
    paddingTop: Dimensions.get('window').width * 0.02,
    fontSize: 14,
  },
  messageBox: {
    width: Dimensions.get('window').width * 0.9,
    height: 100,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: '#bfbebe',
  },
  manageSendMessagebtn: {
    borderRadius: 20,
    flexDirection: 'row',
    paddingVertical: 8,
    justifyContent: 'center',
    alignSelf: 'flex-end',
    backgroundColor: '#1784B2',
    width: 200,
    height: 40,
    borderWidth: 1,
    borderColor: '#28527A',
    marginTop: 10,
    alignContent: 'center',
    elevation: 10,
    shadowColor: '#000',
  },
  manageSendMessagebtnText: {
    color: '#FBEEAC',
    fontSize: 16,
    fontWeight: 'bold',
  },
  MessagebtnInManage: {
    backgroundColor: '#abd873',
    width: 70,
    height: 35,
    borderRadius: 30,
    marginHorizontal: 5,
    marginVertical: 25,
  },
  MessagebtnInManageText: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
    paddingTop: Dimensions.get('window').width * 0.02,
    fontSize: 14,
  },
  name: {
    marginLeft: 45,
    fontSize: 24,
    // fontWeight: 'bold',
    color: '#28527A',
  },
  nameheader: {
    flex: 9,
    alignItems: 'center',
    width: 'auto',
    borderRadius: 50,
    justifyContent: 'center',
  },
  cardForAttendees: {
    width: Dimensions.get('window').width * 0.875,
    height: Dimensions.get('window').width * 0.2,
    backgroundColor: '#ffffff',
    borderRadius: 10,
    shadowColor: 'bebebe',
    shadowOffset: {
      width: 0,
      height: -10,
    },
    shadowRadius: 10,
    elevation: 4,
    marginTop: Dimensions.get('window').width * 0.04,
    marginLeft: Dimensions.get('window').width * 0.025,
    marginBottom: 5,
  },
  reachLimitNum: {
    fontSize: 18,
    color: 'red',
    marginTop: 10,
    marginLeft: 50,
  },
  signupIndex: {
    color: '#000',
    fontSize: 15,
  },
  underLimitNum: {
    fontSize: 18,
    color: '#abd873',
    marginTop: 10,
    marginLeft: 50,
  },
  NoLimitNum: {
    fontSize: 18,
    color: '#abd873',
    marginTop: 10,
    marginLeft: 15,
  },
  manageBtn: {
    alignContent: 'flex-end',
    marginLeft: 1,
  },
  removeBox: {
    width: 350,
  },
});
