import { StyleSheet, Dimensions } from 'react-native';

export default StyleSheet.create({
  avatar: {
    margin: 10,
    width: 60,
    height: 60,
    borderRadius: 30,
    borderBottomWidth: 2,
    borderBottomEndRadius: 10,
    borderEndColor: '#bfbebe',
  },
  container: {
    flex: 1,
    flexDirection: 'column',
    alignContent: 'center',
    marginTop: 50,
    marginHorizontal: 15,
    // marginHorizontal: Dimensions.get('window').width * 0.07,
  },
  cardForAttendees: {
    height: 90,
    width: Dimensions.get('window').width * 0.9,
    borderRadius: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#000',
    marginTop: 15,
    flexDirection: 'row',
    shadowColor: '#000',
  },
  DeletebtnInManage: {
    backgroundColor: 'red',
    width: 70,
    height: 35,
    borderRadius: 30,
    marginHorizontal: 5,
    marginVertical: 25,
  },
  DeletebtnInManageText: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
    paddingTop: 10,
  },
  messageBox: {
    width: Dimensions.get('window').width * 0.9,
    height: 100,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: '#bfbebe',
  },
  manageSendMessagebtn: {
    borderRadius: 20,
    flexDirection: 'row',
    paddingVertical: 8,
    justifyContent: 'center',
    alignSelf: 'flex-end',
    backgroundColor: '#1784B2',
    width: 200,
    height: 40,
    borderWidth: 1,
    borderColor: '#28527A',
    marginTop: 10,
    alignContent: 'center',
    elevation: 10,
    shadowColor: '#000',
  },
  manageSendMessagebtnText: {
    color: '#FBEEAC',
    fontSize: 16,
    fontWeight: 'bold',
  },
  MessagebtnInManage: {
    backgroundColor: 'green',
    width: 70,
    height: 35,
    borderRadius: 30,
    marginHorizontal: 5,
    marginVertical: 25,
  },
  MessagebtnInManageText: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
    paddingTop: 10,
  },
  name: {
    marginLeft: 45,
    fontSize: 24,
    // fontWeight: 'bold',
    color: '#28527A',
  },
  nameheader: {
    flex: 9,
    alignItems: 'center',
    width: 'auto',
    borderRadius: 50,
    justifyContent: 'center',
  },
  participantsBox: {
    width: Dimensions.get('window').width * 0.9,
    alignItems: 'center',
    // marginHorizontal: 7,
  },
  reachLimitNum: {
    fontSize: 18,
    color: 'red',
    marginTop: 10,
    marginLeft: 50,
  },
  signupIndex: {
    color: '#000',
    fontSize: 15,
  },
  underLimitNum: {
    fontSize: 18,
    color: 'lightgreen',
    marginTop: 10,
    marginLeft: 50,
  },

});
