import { StyleSheet, Dimensions } from 'react-native';

export default StyleSheet.create({
  body: {
    flex: 1,
  },
  btnPress: {
    height: 40,
    width: 90,
    backgroundColor: '#28527A',
    justifyContent: 'center',
    borderRadius: 5,
    margin: 10,
  },
  btnNormal: {
    height: 40,
    width: 90,
    justifyContent: 'center',
    borderRadius: 5,
    backgroundColor: '#E5EBF1',
    margin: 10,
  },
  btnText: {
    textAlign: 'center',
    fontSize: 16,
    color: '#28527A',
  },
  btnPText: {
    textAlign: 'center',
    fontSize: 16,
    color: '#FBEEAC',
  },
  bodyforCostAndLimitnum: {
    flexDirection: 'row',
  },
  container: {
    flex: 1,
    flexDirection: 'column',
    alignContent: 'center',
    marginTop: 50,
    marginHorizontal: 15,
    // marginHorizontal: Dimensions.get('window').width * 0.07,
  },
  categorybutton: {
    flexWrap: 'wrap',
    flexDirection: 'row',
  },
  CostTitle: {
    flex: 1.4,
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 5,
  },
  CostBox: {
    width: Dimensions.get('window').width * 0.37,
    height: 40,
    borderWidth: 1,
    borderColor: '#bfbebe',
    marginTop: 5,
    marginBottom: 20,
    borderRadius: 5,
  },
  CostAndLimitnumText: {
    width: '100%',
    fontSize: 14,
    fontWeight: 'bold',
    color: 'black',
    height: 35,
    borderRadius: 5,
    textAlign: 'left',
    textAlignVertical: 'center',
  },
  Cloudicon: {
    marginTop: 9,
    color: 'white',
    fontSize: 14,
    marginLeft: 8,
  },
  details: {
    height: 80,
    borderWidth: 1,
    borderColor: '#bfbebe',
    marginTop: 5,
    marginBottom: 20,
    borderRadius: 5,
  },
  footer: {
    height: 'auto',
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
  },
  input: {
    width: '100%',
    fontSize: 16,
    color: 'black',
    height: 35,
    borderRadius: 5,
    marginLeft: 10,
    textAlign: 'left',
    textAlignVertical: 'center',
  },
  inputbox: {
    height: 40,
    borderWidth: 1,
    borderColor: '#bfbebe',
    marginTop: 5,
    marginBottom: 20,
    borderRadius: 5,
  },
  inputboxText: {
    fontSize: 16,
    fontWeight: 'bold',
    alignItems: 'flex-start',
    textAlign: 'left',
    marginLeft: 5,
  },
  image: {
    width: 85,
    height: 85,
    alignItems: 'center',
    marginTop: 5,
    backgroundColor: '#4169E1',
  },
  imageButton: {
    width: 160,
    height: 40,
    alignItems: 'center',
    borderRadius: 4,
    marginTop: 5,
    flexDirection: 'row',
    backgroundColor: '#28527A',
  },
  LimitnumTitle: {
    flex: 1.3,
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 5,
  },
  LimitnumBox: {
    width: Dimensions.get('window').width * 0.37,
    height: 40,
    borderWidth: 1,
    borderColor: '#bfbebe',
    marginTop: 5,
    marginBottom: 20,
    marginLeft: 50,
    borderRadius: 5,
  },
  name: {
    marginLeft: 45,
    fontSize: 24,
    // fontWeight: 'bold',
    color: '#28527A',
  },
  nameheader: {
    flex: 9,
    alignItems: 'center',
    width: 'auto',
    borderRadius: 50,
    justifyContent: 'center',
  },
  text: {
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 'bold',
    marginTop: Dimensions.get('window').width * 0.001,
    fontSize: Dimensions.get('window').width * 0.03,
  },
  unsentButton: {
    borderRadius: 30,
    width: 297,
    height: 48,
    paddingVertical: 8,
    marginVertical: 51,
    backgroundColor: '#D4D4D4',
    elevation: 20,
    shadowColor: '#000',
  },
  unsentButtonText: {
    fontSize: 24,
    textAlign: 'center',
    color: '#737373',
    fontWeight: 'bold',
  },
  sentButton: {
    borderRadius: 30,
    width: 297,
    height: 48,
    paddingVertical: 8,
    marginVertical: 51,
    elevation: 20,
    shadowColor: '#000',
  },
  sentButtonText: {
    fontSize: 24,
    textAlign: 'center',
    color: '#FBEEAC',
    fontWeight: 'bold',
  },
});
