/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginImport } from './routes/login'
import { Route as CallbackImport } from './routes/callback'
import { Route as IndexImport } from './routes/index'
import { Route as SalesIndexImport } from './routes/sales/index'
import { Route as OrderIndexImport } from './routes/order/index'
import { Route as MapIndexImport } from './routes/map/index'
import { Route as EventsIndexImport } from './routes/events/index'
import { Route as DinnerIndexImport } from './routes/dinner/index'
import { Route as CalendarIndexImport } from './routes/calendar/index'
import { Route as OrderMainImport } from './routes/order/main'
import { Route as OrderJoinImport } from './routes/order/join'
import { Route as OrderCreateImport } from './routes/order/create'
import { Route as HomeProfileImport } from './routes/home/profile'
import { Route as EventsSelectImport } from './routes/events/select'
import { Route as EventsCreateImport } from './routes/events/create'
import { Route as EventsEventIdImport } from './routes/events/$eventId'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const CallbackRoute = CallbackImport.update({
  path: '/callback',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SalesIndexRoute = SalesIndexImport.update({
  path: '/sales/',
  getParentRoute: () => rootRoute,
} as any)

const OrderIndexRoute = OrderIndexImport.update({
  path: '/order/',
  getParentRoute: () => rootRoute,
} as any)

const MapIndexRoute = MapIndexImport.update({
  path: '/map/',
  getParentRoute: () => rootRoute,
} as any)

const EventsIndexRoute = EventsIndexImport.update({
  path: '/events/',
  getParentRoute: () => rootRoute,
} as any)

const DinnerIndexRoute = DinnerIndexImport.update({
  path: '/dinner/',
  getParentRoute: () => rootRoute,
} as any)

const CalendarIndexRoute = CalendarIndexImport.update({
  path: '/calendar/',
  getParentRoute: () => rootRoute,
} as any)

const OrderMainRoute = OrderMainImport.update({
  path: '/order/main',
  getParentRoute: () => rootRoute,
} as any)

const OrderJoinRoute = OrderJoinImport.update({
  path: '/order/join',
  getParentRoute: () => rootRoute,
} as any)

const OrderCreateRoute = OrderCreateImport.update({
  path: '/order/create',
  getParentRoute: () => rootRoute,
} as any)

const HomeProfileRoute = HomeProfileImport.update({
  path: '/home/profile',
  getParentRoute: () => rootRoute,
} as any)

const EventsSelectRoute = EventsSelectImport.update({
  path: '/events/select',
  getParentRoute: () => rootRoute,
} as any)

const EventsCreateRoute = EventsCreateImport.update({
  path: '/events/create',
  getParentRoute: () => rootRoute,
} as any)

const EventsEventIdRoute = EventsEventIdImport.update({
  path: '/events/$eventId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdImport
      parentRoute: typeof rootRoute
    }
    '/events/create': {
      id: '/events/create'
      path: '/events/create'
      fullPath: '/events/create'
      preLoaderRoute: typeof EventsCreateImport
      parentRoute: typeof rootRoute
    }
    '/events/select': {
      id: '/events/select'
      path: '/events/select'
      fullPath: '/events/select'
      preLoaderRoute: typeof EventsSelectImport
      parentRoute: typeof rootRoute
    }
    '/home/profile': {
      id: '/home/profile'
      path: '/home/profile'
      fullPath: '/home/profile'
      preLoaderRoute: typeof HomeProfileImport
      parentRoute: typeof rootRoute
    }
    '/order/create': {
      id: '/order/create'
      path: '/order/create'
      fullPath: '/order/create'
      preLoaderRoute: typeof OrderCreateImport
      parentRoute: typeof rootRoute
    }
    '/order/join': {
      id: '/order/join'
      path: '/order/join'
      fullPath: '/order/join'
      preLoaderRoute: typeof OrderJoinImport
      parentRoute: typeof rootRoute
    }
    '/order/main': {
      id: '/order/main'
      path: '/order/main'
      fullPath: '/order/main'
      preLoaderRoute: typeof OrderMainImport
      parentRoute: typeof rootRoute
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarIndexImport
      parentRoute: typeof rootRoute
    }
    '/dinner/': {
      id: '/dinner/'
      path: '/dinner'
      fullPath: '/dinner'
      preLoaderRoute: typeof DinnerIndexImport
      parentRoute: typeof rootRoute
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsIndexImport
      parentRoute: typeof rootRoute
    }
    '/map/': {
      id: '/map/'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapIndexImport
      parentRoute: typeof rootRoute
    }
    '/order/': {
      id: '/order/'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderIndexImport
      parentRoute: typeof rootRoute
    }
    '/sales/': {
      id: '/sales/'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/create': typeof EventsCreateRoute
  '/events/select': typeof EventsSelectRoute
  '/home/profile': typeof HomeProfileRoute
  '/order/create': typeof OrderCreateRoute
  '/order/join': typeof OrderJoinRoute
  '/order/main': typeof OrderMainRoute
  '/calendar': typeof CalendarIndexRoute
  '/dinner': typeof DinnerIndexRoute
  '/events': typeof EventsIndexRoute
  '/map': typeof MapIndexRoute
  '/order': typeof OrderIndexRoute
  '/sales': typeof SalesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/create': typeof EventsCreateRoute
  '/events/select': typeof EventsSelectRoute
  '/home/profile': typeof HomeProfileRoute
  '/order/create': typeof OrderCreateRoute
  '/order/join': typeof OrderJoinRoute
  '/order/main': typeof OrderMainRoute
  '/calendar': typeof CalendarIndexRoute
  '/dinner': typeof DinnerIndexRoute
  '/events': typeof EventsIndexRoute
  '/map': typeof MapIndexRoute
  '/order': typeof OrderIndexRoute
  '/sales': typeof SalesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/create': typeof EventsCreateRoute
  '/events/select': typeof EventsSelectRoute
  '/home/profile': typeof HomeProfileRoute
  '/order/create': typeof OrderCreateRoute
  '/order/join': typeof OrderJoinRoute
  '/order/main': typeof OrderMainRoute
  '/calendar/': typeof CalendarIndexRoute
  '/dinner/': typeof DinnerIndexRoute
  '/events/': typeof EventsIndexRoute
  '/map/': typeof MapIndexRoute
  '/order/': typeof OrderIndexRoute
  '/sales/': typeof SalesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/login'
    | '/signup'
    | '/events/$eventId'
    | '/events/create'
    | '/events/select'
    | '/home/profile'
    | '/order/create'
    | '/order/join'
    | '/order/main'
    | '/calendar'
    | '/dinner'
    | '/events'
    | '/map'
    | '/order'
    | '/sales'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/login'
    | '/signup'
    | '/events/$eventId'
    | '/events/create'
    | '/events/select'
    | '/home/profile'
    | '/order/create'
    | '/order/join'
    | '/order/main'
    | '/calendar'
    | '/dinner'
    | '/events'
    | '/map'
    | '/order'
    | '/sales'
  id:
    | '__root__'
    | '/'
    | '/callback'
    | '/login'
    | '/signup'
    | '/events/$eventId'
    | '/events/create'
    | '/events/select'
    | '/home/profile'
    | '/order/create'
    | '/order/join'
    | '/order/main'
    | '/calendar/'
    | '/dinner/'
    | '/events/'
    | '/map/'
    | '/order/'
    | '/sales/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackRoute: typeof CallbackRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsCreateRoute: typeof EventsCreateRoute
  EventsSelectRoute: typeof EventsSelectRoute
  HomeProfileRoute: typeof HomeProfileRoute
  OrderCreateRoute: typeof OrderCreateRoute
  OrderJoinRoute: typeof OrderJoinRoute
  OrderMainRoute: typeof OrderMainRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
  DinnerIndexRoute: typeof DinnerIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  MapIndexRoute: typeof MapIndexRoute
  OrderIndexRoute: typeof OrderIndexRoute
  SalesIndexRoute: typeof SalesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackRoute: CallbackRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  EventsCreateRoute: EventsCreateRoute,
  EventsSelectRoute: EventsSelectRoute,
  HomeProfileRoute: HomeProfileRoute,
  OrderCreateRoute: OrderCreateRoute,
  OrderJoinRoute: OrderJoinRoute,
  OrderMainRoute: OrderMainRoute,
  CalendarIndexRoute: CalendarIndexRoute,
  DinnerIndexRoute: DinnerIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  MapIndexRoute: MapIndexRoute,
  OrderIndexRoute: OrderIndexRoute,
  SalesIndexRoute: SalesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/callback",
        "/login",
        "/signup",
        "/events/$eventId",
        "/events/create",
        "/events/select",
        "/home/profile",
        "/order/create",
        "/order/join",
        "/order/main",
        "/calendar/",
        "/dinner/",
        "/events/",
        "/map/",
        "/order/",
        "/sales/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/callback": {
      "filePath": "callback.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/events/$eventId": {
      "filePath": "events/$eventId.tsx"
    },
    "/events/create": {
      "filePath": "events/create.tsx"
    },
    "/events/select": {
      "filePath": "events/select.tsx"
    },
    "/home/profile": {
      "filePath": "home/profile.tsx"
    },
    "/order/create": {
      "filePath": "order/create.tsx"
    },
    "/order/join": {
      "filePath": "order/join.tsx"
    },
    "/order/main": {
      "filePath": "order/main.tsx"
    },
    "/calendar/": {
      "filePath": "calendar/index.tsx"
    },
    "/dinner/": {
      "filePath": "dinner/index.tsx"
    },
    "/events/": {
      "filePath": "events/index.tsx"
    },
    "/map/": {
      "filePath": "map/index.tsx"
    },
    "/order/": {
      "filePath": "order/index.tsx"
    },
    "/sales/": {
      "filePath": "sales/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
