create table "public"."food_category" (
    "id" integer generated by default as identity not null,
    "food_category" text not null
);


alter table "public"."food_category" enable row level security;

create table "public"."restaurants" (
    "id" bigint generated by default as identity not null,
    "openhr" text not null,
    "address" text,
    "location" smallint,
    "openday" smallint[],
    "restaurant" text,
    "image" text,
    "menu" text,
    "fk_category" integer not null
);


alter table "public"."restaurants" enable row level security;

CREATE UNIQUE INDEX food_category_pkey ON public.food_category USING btree (id);

CREATE UNIQUE INDEX restaurants_pkey ON public.restaurants USING btree (id);

alter table "public"."food_category" add constraint "food_category_pkey" PRIMARY KEY using index "food_category_pkey";

alter table "public"."restaurants" add constraint "restaurants_pkey" PRIMARY KEY using index "restaurants_pkey";

alter table "public"."restaurants" add constraint "restaurants_fk_category_fkey" FOREIGN KEY (fk_category) REFERENCES food_category(id) not valid;

alter table "public"."restaurants" validate constraint "restaurants_fk_category_fkey";

grant delete on table "public"."food_category" to "anon";

grant insert on table "public"."food_category" to "anon";

grant references on table "public"."food_category" to "anon";

grant select on table "public"."food_category" to "anon";

grant trigger on table "public"."food_category" to "anon";

grant truncate on table "public"."food_category" to "anon";

grant update on table "public"."food_category" to "anon";

grant delete on table "public"."food_category" to "authenticated";

grant insert on table "public"."food_category" to "authenticated";

grant references on table "public"."food_category" to "authenticated";

grant select on table "public"."food_category" to "authenticated";

grant trigger on table "public"."food_category" to "authenticated";

grant truncate on table "public"."food_category" to "authenticated";

grant update on table "public"."food_category" to "authenticated";

grant delete on table "public"."food_category" to "service_role";

grant insert on table "public"."food_category" to "service_role";

grant references on table "public"."food_category" to "service_role";

grant select on table "public"."food_category" to "service_role";

grant trigger on table "public"."food_category" to "service_role";

grant truncate on table "public"."food_category" to "service_role";

grant update on table "public"."food_category" to "service_role";

grant delete on table "public"."restaurants" to "anon";

grant insert on table "public"."restaurants" to "anon";

grant references on table "public"."restaurants" to "anon";

grant select on table "public"."restaurants" to "anon";

grant trigger on table "public"."restaurants" to "anon";

grant truncate on table "public"."restaurants" to "anon";

grant update on table "public"."restaurants" to "anon";

grant delete on table "public"."restaurants" to "authenticated";

grant insert on table "public"."restaurants" to "authenticated";

grant references on table "public"."restaurants" to "authenticated";

grant select on table "public"."restaurants" to "authenticated";

grant trigger on table "public"."restaurants" to "authenticated";

grant truncate on table "public"."restaurants" to "authenticated";

grant update on table "public"."restaurants" to "authenticated";

grant delete on table "public"."restaurants" to "service_role";

grant insert on table "public"."restaurants" to "service_role";

grant references on table "public"."restaurants" to "service_role";

grant select on table "public"."restaurants" to "service_role";

grant trigger on table "public"."restaurants" to "service_role";

grant truncate on table "public"."restaurants" to "service_role";

grant update on table "public"."restaurants" to "service_role";


