drop policy "Enable read access for all users" on "public"."food_category";

drop policy "Enable read access for all users" on "public"."restaurants";

revoke delete on table "public"."food_category" from "anon";

revoke insert on table "public"."food_category" from "anon";

revoke references on table "public"."food_category" from "anon";

revoke select on table "public"."food_category" from "anon";

revoke trigger on table "public"."food_category" from "anon";

revoke truncate on table "public"."food_category" from "anon";

revoke update on table "public"."food_category" from "anon";

revoke delete on table "public"."food_category" from "authenticated";

revoke insert on table "public"."food_category" from "authenticated";

revoke references on table "public"."food_category" from "authenticated";

revoke select on table "public"."food_category" from "authenticated";

revoke trigger on table "public"."food_category" from "authenticated";

revoke truncate on table "public"."food_category" from "authenticated";

revoke update on table "public"."food_category" from "authenticated";

revoke delete on table "public"."food_category" from "service_role";

revoke insert on table "public"."food_category" from "service_role";

revoke references on table "public"."food_category" from "service_role";

revoke select on table "public"."food_category" from "service_role";

revoke trigger on table "public"."food_category" from "service_role";

revoke truncate on table "public"."food_category" from "service_role";

revoke update on table "public"."food_category" from "service_role";

revoke delete on table "public"."restaurants" from "anon";

revoke insert on table "public"."restaurants" from "anon";

revoke references on table "public"."restaurants" from "anon";

revoke select on table "public"."restaurants" from "anon";

revoke trigger on table "public"."restaurants" from "anon";

revoke truncate on table "public"."restaurants" from "anon";

revoke update on table "public"."restaurants" from "anon";

revoke delete on table "public"."restaurants" from "authenticated";

revoke insert on table "public"."restaurants" from "authenticated";

revoke references on table "public"."restaurants" from "authenticated";

revoke select on table "public"."restaurants" from "authenticated";

revoke trigger on table "public"."restaurants" from "authenticated";

revoke truncate on table "public"."restaurants" from "authenticated";

revoke update on table "public"."restaurants" from "authenticated";

revoke delete on table "public"."restaurants" from "service_role";

revoke insert on table "public"."restaurants" from "service_role";

revoke references on table "public"."restaurants" from "service_role";

revoke select on table "public"."restaurants" from "service_role";

revoke trigger on table "public"."restaurants" from "service_role";

revoke truncate on table "public"."restaurants" from "service_role";

revoke update on table "public"."restaurants" from "service_role";

alter table "public"."restaurants" drop constraint "restaurants_fk_category_fkey";

alter table "public"."food_category" drop constraint "food_category_pkey";

alter table "public"."restaurants" drop constraint "restaurants_pkey";

drop index if exists "public"."food_category_pkey";

drop index if exists "public"."restaurants_pkey";

drop table "public"."food_category";

drop table "public"."restaurants";

create table "public"."order" (
    "order_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "restaurant" text,
    "order_link" text,
    "due" timestamp without time zone,
    "main" uuid default gen_random_uuid(),
    "add" text[] not null
);


alter table "public"."order" enable row level security;

CREATE UNIQUE INDEX order_pkey ON public."order" USING btree (order_id);

alter table "public"."order" add constraint "order_pkey" PRIMARY KEY using index "order_pkey";

alter table "public"."order" add constraint "order_main_fkey" FOREIGN KEY (main) REFERENCES members(uuid) not valid;

alter table "public"."order" validate constraint "order_main_fkey";

grant delete on table "public"."order" to "anon";

grant insert on table "public"."order" to "anon";

grant references on table "public"."order" to "anon";

grant select on table "public"."order" to "anon";

grant trigger on table "public"."order" to "anon";

grant truncate on table "public"."order" to "anon";

grant update on table "public"."order" to "anon";

grant delete on table "public"."order" to "authenticated";

grant insert on table "public"."order" to "authenticated";

grant references on table "public"."order" to "authenticated";

grant select on table "public"."order" to "authenticated";

grant trigger on table "public"."order" to "authenticated";

grant truncate on table "public"."order" to "authenticated";

grant update on table "public"."order" to "authenticated";

grant delete on table "public"."order" to "service_role";

grant insert on table "public"."order" to "service_role";

grant references on table "public"."order" to "service_role";

grant select on table "public"."order" to "service_role";

grant trigger on table "public"."order" to "service_role";

grant truncate on table "public"."order" to "service_role";

grant update on table "public"."order" to "service_role";


