name: Linting Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
    - name: RUN ESLint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx
