name: Check Code Style and Types

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - run: npm ci

    - name: Type check
      run: npm run build

    - name: Code style check
      run: npm run lint
