name: Release App

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
    - name: Install Expo-CLI
      run: npm install -g expo-cli
    - name: Login Expo
      env:
        EXPO_CLI_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}
      run: npx expo login --non-interactive -u NCUAppTeam
    - name: Publish build
      run: npx expo publish --non-interactive

  release_android:
    runs-on: ubuntu-latest
    needs: publish
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Use Java 8
      uses: actions/setup-java@v1
      with:
        java-version: '8'
    - run: npm ci
    - name: Install Turtle-CLI 
      run: npm install -g turtle-cli
    - name: Extract KeyStore
      env:
        BASE64_ENCODED: ${{ secrets.ANDROID_KEYSTORE }}
      run: echo "$BASE64_ENCODED" | base64 -d > ./KeyStore.jks
    - name: Build App
      env:
        EXPO_USERNAME: ncuappteam
        EXPO_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}
        EXPO_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.EXPO_ANDROID_KEYSTORE_PASSWORD }}
        EXPO_ANDROID_KEY_PASSWORD: ${{ secrets.EXPO_ANDROID_KEY_PASSWORD }}
      run:  turtle build:android --keystore-path ./KeyStore.jks --keystore-alias tw.edu.ncu.app --type app-bundle -o NCU-App-$(date +'%Y-%m-%d').aab
    # TODO, automatically upload .aab file to play store
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: android-bundle
        path: ./*.aab

  release_ios:
    runs-on: macos-latest
    needs: publish
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
    - name: Install Turtle-CLI 
      run: npm install -g turtle-cli
    - name: Extract P12
      env:
        BASE64_ENCODED: ${{ secrets.APPLE_CERT_P12 }}
      run: echo "$BASE64_ENCODED" | base64 -d > ./cert.p12
    - name: Extract Provisioning profile
      env:
        BASE64_ENCODED: ${{ secrets.APPLE_PROFILE_MOBILEPROVISION }}
      run: echo "$BASE64_ENCODED" | base64 -d > ./profile.mobileprovision
    - name: Build App
      env:
        EXPO_USERNAME: ncuappteam
        EXPO_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}
        EXPO_IOS_DIST_P12_PASSWORD: ${{ secrets.EXPO_IOS_DIST_P12_PASSWORD }}
      run:  turtle build:ios --team-id 8AWNGKT5GW --dist-p12-path ./cert.p12 --provisioning-profile-path ./profile.mobileprovision -o NCU-App.ipa
    - name: Validate App
      run: xcrun altool --validate-app -f NCU-App.ipa -t ios -u ncuappteam@gmail.com -p ${{ secrets.APPLE_PASSWORD }}
    - name: Upload App
      run: xcrun altool --upload-app -f NCU-App.ipa -t ios -u ncuappteam@gmail.com -p ${{ secrets.APPLE_PASSWORD }}
